# Generated by Django 3.2.25 on 2024-10-04 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoviews',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 8, 52, 23, 955486)),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 8, 52, 23, 955438)),
        ),
    ]
